set nocompatible

let g:loaded_matchparen = 1
packadd! matchit

call plug#begin('~/.vim/plugged')
Plug 'ctrlpvim/ctrlp.vim'
Plug 'gruvbox-community/gruvbox'
Plug 'luochen1990/rainbow'
call plug#end()

let g:rainbow_active = 1

set autoindent
set autoread
set backspace=indent,eol,start
set colorcolumn=81
set encoding=utf-8
set fileencoding=utf-8
set formatoptions+=j
set formatoptions-=c
set formatoptions-=t
set hidden
set ignorecase
set incsearch
set laststatus=2
set lazyredraw
set listchars=tab:▸\ ,eol:¬,space:.
set mouse=a
set nobackup
set nohlsearch
set nojoinspaces
set number
set ruler
set scrolloff=3
set shortmess+=I
set smartcase
set spelllang=en_us,sl
set splitbelow
set splitright
set textwidth=80
set viminfo='50,\"100,:100,%,n~/.viminfo
set writebackup

set wildmenu
set wildignore=*.o

set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4

if has('gui_running')
  set guioptions-=m
  set guioptions-=T
  set guioptions-=r
  set guioptions-=L
endif

" Change the cursor to a line when in INSERT mode, and back to a bar when in
" NORMAL mode. Do this only in xterm and rxvt terminal emulators.
if match(&term, 'xterm') != -1 || match(&term, 'rxvt') != -1
  let &t_EI = "\e[2 q"
  let &t_SI = "\e[6 q"
  let &t_SR = "\e[4 q"
endif

if has('unnamedplus')
  set clipboard=unnamedplus
else
  set clipboard=unnamed
endif

set statusline=%f\                 " Filename
set statusline+=%h                 " Help flag
set statusline+=%m                 " Modified flag
set statusline+=%r                 " Read-only flag
set statusline+=%=                 " Separation point
set statusline+=%y                 " Filetype
set statusline+=[%{&fileformat}]   " File format (line ending)
set statusline+=[%{&fileencoding}] " File encoding
set statusline+=\ [%04l/%04L]      " Line info
set statusline+=[%04c-%04v]        " Column info

let g:ctrlp_cmd = 'CtrlPMixed'

syntax on
set background=dark

let g:gruvbox_contrast_dark = 'hard'
colorscheme gruvbox

highlight ExtraWhitespace cterm=underline ctermfg=red

function! HSort()
  let l:curpos = getpos('.')[2]
  let l:str = getline('.')[curpos-1:]
  call append(line('.'), join(sort(split(str, ' ')), ' '))
  execute 'normal! d$J'
endfunction

inoremap jk <ESC>
nnoremap <silent> <leader>e :e $MYVIMRC<CR>
nnoremap <silent> <leader>l :set list!<CR>
nnoremap <silent> <leader>s :call HSort()<CR>

" Some common typos...
command! -bang -nargs=? -complete=file W w<bang> <args>
command! -bang -nargs=? -complete=file Wq wq<bang> <args>
command! -bang -nargs=? -complete=file WQ wq<bang> <args>
command! -bang Q q<bang>
command! -bang Qa qa<bang>
command! -bang QA qa<bang>

filetype plugin indent on

augroup np_au
  autocmd!
  autocmd BufReadPost * if line("'\"") | exe "'\"" | endif " restore cursor pos
  autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
  autocmd ColorScheme * highlight ExtraWhitespace cterm=underline ctermfg=red

  autocmd BufRead,BufNewFile *.h setl filetype=c
  autocmd FileType markdown setl fo-=t spell
  autocmd FileType c :call openbsd#OpenBSD_Style()
  autocmd FileType cpp setl cindent cino=:0,g0,l1,N-s et fo-=c fo-=t sts=4 sw=4 ts=4
  autocmd FileType css setl et sts=2 sw=2 ts=2
  autocmd FileType gitcommit setl spell
  autocmd FileType hgcommit setl spell
  autocmd FileType html setl et sts=2 sw=2 ts=2
  autocmd FileType pascal setl et sts=2 sw=2 ts=2
  autocmd FileType vim setl et sts=2 sw=2 ts=2
  autocmd FileType xml setl et sts=2 sw=2 ts=2
augroup END
