set nocompatible

packadd! matchit

set autoindent
set autoread
set backspace=indent,eol,start
set colorcolumn=81
set encoding=utf-8
set fileencoding=utf-8
set formatoptions+=j
set formatoptions-=c
set formatoptions-=t
set hidden
set ignorecase
set incsearch
set laststatus=2
set lazyredraw
set listchars=tab:▸\ ,eol:¬,space:.
set mouse=a
set nobackup
set nohlsearch
set nojoinspaces
set number
set ruler
set scrolloff=3
set shortmess+=I
set showmatch
set smartcase
set spelllang=en_us,sl
set splitbelow
set splitright
set textwidth=80
set writebackup

set wildmenu
set wildignore=*.o

set noexpandtab
set shiftwidth=8
set softtabstop=8
set tabstop=8

if has('gui_running')
  set guioptions-=m
  set guioptions-=T
  set guioptions-=r
  set guioptions-=L
endif

" Change the cursor to a line when in INSERT mode, and back to a bar when in
" NORMAL mode. Do this only in xterm and rxvt terminal emulators.
if match(&term, 'xterm') != -1 || match(&term, 'rxvt') != -1
  let &t_EI = "\e[2 q"
  let &t_SI = "\e[6 q"
  let &t_SR = "\e[4 q"
endif

if has('unnamedplus')
  set clipboard=unnamedplus
else
  set clipboard=unnamed
endif

set statusline=%f\                 " Filename
set statusline+=%h                 " Help flag
set statusline+=%m                 " Modified flag
set statusline+=%r                 " Read-only flag
set statusline+=%=                 " Separation point
set statusline+=%y                 " Filetype
set statusline+=[%{&fileformat}]   " File format (line ending)
set statusline+=[%{&fileencoding}] " File encoding
set statusline+=\ [%04l/%04L]      " Line info
set statusline+=[%04c-%04v]        " Column info

let g:ctrlp_cmd = 'CtrlPMixed'

syntax on
set background=dark

colorscheme ron

highlight ColorColumn ctermbg=darkgrey guibg=lightgrey
highlight Comment cterm=bold ctermfg=none
highlight CursorLine cterm=bold
highlight ExtraWhitespace cterm=underline ctermfg=red
highlight NonText ctermfg=darkgrey
highlight Pmenu ctermbg=white ctermfg=black
highlight PmenuSel ctermbg=darkcyan ctermfg=black
highlight PreProc ctermfg=grey
highlight Search ctermbg=12
highlight SpecialKey ctermfg=darkgrey
highlight SpellBad cterm=underline ctermfg=red ctermbg=none
highlight SpellLocal cterm=underline ctermfg=cyan ctermbg=none
highlight StatusLine cterm=none ctermbg=lightgrey ctermfg=black
highlight StatusLineNC cterm=none ctermbg=none ctermfg=darkgrey
highlight String ctermfg=darkblue cterm=italic
highlight TabLine cterm=none ctermfg=darkgrey ctermbg=none
highlight TabLineFill cterm=none
highlight Title cterm=none ctermfg=darkgrey
highlight Todo ctermbg=NONE ctermfg=red cterm=bold
highlight Type ctermfg=darkblue
highlight cIncluded ctermfg=NONE cterm=bold
highlight clear SignColumn
highlight hareKeyword ctermbg=NONE ctermfg=darkcyan
highlight jsParensError ctermbg=NONE
highlight lineNr ctermfg=grey cterm=italic
highlight pythonBuiltin ctermfg=darkcyan
highlight pythonConditional ctermfg=darkcyan
highlight pythonInclude ctermfg=blue

function! HSort()
  let l:curpos = getpos('.')[2]
  let l:str = getline('.')[curpos-1:]
  call append(line('.'), join(sort(split(str, ' ')), ' '))
  execute 'normal! d$J'
endfunction

inoremap jk <ESC>
nnoremap <silent> <leader>e :e $MYVIMRC<CR>
nnoremap <silent> <leader>l :set list!<CR>
nnoremap <silent> <leader>s :call HSort()<CR>

filetype plugin indent on

augroup np_au
  autocmd!
  autocmd ColorScheme * highlight ExtraWhitespace cterm=underline ctermfg=red
  autocmd BufWinEnter * match ExtraWhitespace /\s\+$/

  autocmd BufRead,BufNewFile *.h setl filetype=c
  autocmd FileType asciidoc setl spell
  autocmd FileType c :call openbsd#OpenBSD_Style()
  autocmd FileType cpp setl cindent cino=:0,g0,l1,N-s fo-=c fo-=t noet sts=8 sw=8 ts=8
  autocmd FileType gitcommit setl spell
  autocmd FileType hgcommit setl spell
  autocmd FileType html setl et sts=2 sw=2 ts=2
  autocmd FileType meson setl noet sts=8 sw=8 ts=8
  autocmd FileType python setl et sts=4 sw=4 ts=4
  autocmd FileType vim setl et sts=2 sw=2 ts=2
  autocmd FileType xml setl et sts=2 sw=2 ts=2
augroup END
